// "use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Wrapper from "@/components/Wrapper/Wrapper";
import { Provider } from "react-redux";
import { Providers } from "@/app/GlobalRedux/provider";
import Head from "next/head";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script
        src={
          "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7249338276563886"
        }
      />
      {/*<Head>*/}
      {/*  <title>TEST</title>*/}
      {/*</Head>*/}
      <body className={inter.className}>
        <Providers>
          <Wrapper fileInput> {children}</Wrapper>
        </Providers>
      </body>
    </html>
  );
}
